"""Add active status to users

Revision ID: 060e6f8e8bfa
Revises: 4ce80e28cd77
Create Date: 2023-11-02 15:06:15.606574

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '060e6f8e8bfa'
down_revision = '4ce80e28cd77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
