"""zbritja2 e perqindjes

Revision ID: 1f94c3da1438
Revises: 3ccee2849dda
Create Date: 2023-12-15 15:43:43.905430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f94c3da1438'
down_revision = '3ccee2849dda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('original_price', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('original_price')

    # ### end Alembic commands ###
