"""empty message

Revision ID: 3d7869d16e89
Revises: 2f3c3bc0ca2e
Create Date: 2023-11-07 10:02:30.948533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d7869d16e89'
down_revision = '2f3c3bc0ca2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_constraint('notification_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'product', ['product_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('notification_ibfk_1', 'product', ['product_id'], ['id'])

    # ### end Alembic commands ###
