"""QRCode model added

Revision ID: 3de7cd41537e
Revises: 542d2ebc3333
Create Date: 2023-12-11 14:09:36.112005

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3de7cd41537e'
down_revision = '542d2ebc3333'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('qr_code',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payment_id', sa.String(length=120), nullable=False),
    sa.Column('creation_time', sa.DateTime(), nullable=True),
    sa.Column('valid_duration', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('payment_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('qr_code')
    # ### end Alembic commands ###
