"""Added WashproductImage model

Revision ID: 542d2ebc3333
Revises: 090cccfacb95
Create Date: 2023-12-08 09:50:29.766783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '542d2ebc3333'
down_revision = '090cccfacb95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('washproduct_image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_file', sa.String(length=120), nullable=False),
    sa.Column('washproduct_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['washproduct_id'], ['washproducts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('washproduct_image')
    # ### end Alembic commands ###
