"""empty message

Revision ID: 81012ad6676c
Revises: f69bc7d926b0
Create Date: 2023-11-09 10:59:41.213870

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '81012ad6676c'
down_revision = 'f69bc7d926b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('simple_notification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), nullable=False))
        batch_op.alter_column('creator',
               existing_type=mysql.VARCHAR(length=120),
               type_=sa.String(length=128),
               existing_nullable=False)
        batch_op.drop_index('ix_simple_notification_date')
        batch_op.drop_column('date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('simple_notification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', mysql.DATETIME(), nullable=True))
        batch_op.create_index('ix_simple_notification_date', ['date'], unique=False)
        batch_op.alter_column('creator',
               existing_type=sa.String(length=128),
               type_=mysql.VARCHAR(length=120),
               existing_nullable=False)
        batch_op.drop_column('timestamp')

    # ### end Alembic commands ###
