"""empty message

Revision ID: 9974e9d749b9
Revises: 7f42fe41fff8
Create Date: 2023-11-20 18:59:39.288192

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9974e9d749b9'
down_revision = '7f42fe41fff8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('original_price')
        batch_op.drop_column('current_price')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_price', mysql.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column('original_price', mysql.FLOAT(), nullable=True))

    # ### end Alembic commands ###
