"""empty message

Revision ID: 9eaf6e272a92
Revises: b53b41364293
Create Date: 2023-11-09 10:28:36.936443

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9eaf6e272a92'
down_revision = 'b53b41364293'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('simple_notification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), nullable=True))
        batch_op.drop_index('ix_simple_notification_date')
        batch_op.create_index(batch_op.f('ix_simple_notification_timestamp'), ['timestamp'], unique=False)
        batch_op.drop_column('date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('simple_notification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', mysql.DATETIME(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_simple_notification_timestamp'))
        batch_op.create_index('ix_simple_notification_date', ['date'], unique=False)
        batch_op.drop_column('timestamp')

    # ### end Alembic commands ###
