"""empty message

Revision ID: b06ec018e7c9
Revises: 2017bfd6c699
Create Date: 2023-11-21 09:26:27.305142

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b06ec018e7c9'
down_revision = '2017bfd6c699'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('original_price')
        batch_op.drop_column('current_price')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_price', mysql.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column('original_price', mysql.FLOAT(), nullable=True))

    # ### end Alembic commands ###
