"""empty message

Revision ID: e7ae11cc6869
Revises: 81012ad6676c
Create Date: 2023-11-09 15:41:35.699569

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e7ae11cc6869'
down_revision = '81012ad6676c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('simple_notification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.DateTime(), nullable=True))
        batch_op.alter_column('creator',
               existing_type=mysql.VARCHAR(length=128),
               type_=sa.String(length=120),
               existing_nullable=False)
        batch_op.create_index(batch_op.f('ix_simple_notification_date'), ['date'], unique=False)
        batch_op.drop_column('timestamp')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('simple_notification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', mysql.DATETIME(), nullable=False))
        batch_op.drop_index(batch_op.f('ix_simple_notification_date'))
        batch_op.alter_column('creator',
               existing_type=sa.String(length=120),
               type_=mysql.VARCHAR(length=128),
               existing_nullable=False)
        batch_op.drop_column('date')

    # ### end Alembic commands ###
