"""shfaqja e perqindjes

Revision ID: ea691b4a3276
Revises: 5aed70f37ea4
Create Date: 2023-12-15 11:10:11.164129

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea691b4a3276'
down_revision = '5aed70f37ea4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('discount_percentage', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('discounted_price', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('discounted_price')
        batch_op.drop_column('discount_percentage')

    # ### end Alembic commands ###
