"""empty message

Revision ID: f69bc7d926b0
Revises: 9eaf6e272a92
Create Date: 2023-11-09 10:35:43.877695

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f69bc7d926b0'
down_revision = '9eaf6e272a92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('simple_notification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.DateTime(), nullable=True))
        batch_op.drop_index('ix_simple_notification_timestamp')
        batch_op.create_index(batch_op.f('ix_simple_notification_date'), ['date'], unique=False)
        batch_op.drop_column('timestamp')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('simple_notification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', mysql.DATETIME(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_simple_notification_date'))
        batch_op.create_index('ix_simple_notification_timestamp', ['timestamp'], unique=False)
        batch_op.drop_column('date')

    # ### end Alembic commands ###
